### ISSUE TITLE
IE10 issue Chico v.1 - Input type radio alignment

### ISSUE THREAD

**Issue by andreseichenbaum** [mercadolibre/chico#1070]
In IE10 the input type radio and the respective label are not aligning properly vertically as it shows in the following screenshots.

![screen shot 2013-10-01 at 12 20 53 pm](https://f.cloud.github.com/assets/5272475/1246402/260363fc-2aad-11e3-9c4b-772a38c4dcdd.png)
![screen shot 2013-10-01 at 12 20 26 pm](https://f.cloud.github.com/assets/5272475/1246403/26061a48-2aad-11e3-9393-101818af1f1d.png)

**Comment by hmammana** [comment]
Please review it.
