### ISSUE TITLE
autoComplete: Empezar a mostrar a la caja de sugerencias a partir de n caracteres ingresados.

### ISSUE THREAD

**Issue by eodorizzi** [mercadolibre/chico#1122]
Estuvimos incluyendo el autoComplete para las ciudades, esto trae como consecuencia que en algunos casos tengamos una lista de sugerencias muy grande y por esto sería interesante incluir una opción a este control para que recién empiece a sugerir a partir del ingreso de n caracteres (ej: a partir del tercero) para además de hacer demasiadas consultas al servidor, reducir la longitud de la caja de sugerencias.

**Comment by hmammana** [comment]
It is possible to do without configuration. Yo have to count the amount of characters typed in the input element. You could use the 'type' event. 

```javascript 
autocomplete.on('type', function (userInput) {
    if (userInput.length >= 5) {
        $.ajax();
    }
});
```
