### ISSUE TITLE
ChicoUI - .number validation is not validating floats

### ISSUE THREAD

**Issue by guillermosnipeml** [mercadolibre/chico#1132]
.number won´t validate values like "12,34", or "12.34" due that the regexp only matches integers discarding the value datatype.

Proposed solution:
- force coertion to number like this: +"12,34", and then ask for the returned result with isNaN, if true, the coertion failed, if false it's a number now.
- Keep in mind that as the result of forcing the coertion to number "-12.34" will become a valid number too. (-12.34)

**Comment by battaglr** [comment]
Sadly I'll have to close this since it's not aligned with the project's current objectives. :pensive:

Thanks for opening the issue. :grinning:
