### ISSUE TITLE
Expando & Menu improvements

### ISSUE THREAD

**Issue by pulsovisual** [mercadolibre/chico#1185]
See the images attached.
![expando menu-references](https://f.cloud.github.com/assets/752363/2217989/bc92bf10-9a25-11e3-89c3-d7262a2d2d80.png)
![expando menu](https://f.cloud.github.com/assets/752363/2217990/bc94d944-9a25-11e3-8413-c42a755cd9da.png)

**Comment by atma** [comment]
Almost all recommendations were implemented in #1234 during migration to Sass.
The only thing pending is the `alignment: top` of expandable trigger icon.

**Comment by battaglr** [comment]
Sadly I'll have to close this since it's not aligned with the project's current objectives. :pensive:

Thanks for opening the issue. :grinning:
