### ISSUE TITLE
Mobile CSS: Add a separation between the form and the submit button

### ISSUE THREAD

**Issue by lean8086** [mercadolibre/chico#1189]
Add a separation on the ch-form-actions classname

**Comment by atma** [comment]
Currently the spacing of `ch-form-actions` is handling by additional form components, such as `ch-form-row`. If the actions row should have its personal spacing it can be added in the future release as Sass variables.
Confirmation needed.

**Comment by battaglr** [comment]
I'll close this due to inactivity. If it's still relevant, please, feel free to comment.
