### ISSUE TITLE
**Mobile** Fix padding of `.ch-box-list input+label`

### ISSUE THREAD

**Issue by dcalder** [mercadolibre/chico#1190]
In Mobile the right padding of `.ch-box-list input+label` is missing, it must be `padding: 14px 14px 14px 38px`.

**Comment by hmammana** [comment]
Please review it.

**Comment by dcalder** [comment]
@hmammana parece que ésto se arregló:
https://github.com/mercadolibre/chico/blob/master/src/mobile/css/Form.css#L133

**Comment by atma** [comment]
Closed due to migration to Sass.
The exact value depends on Sass variable. Current default value is defined as `14px 0 14px 38px`.
Mo details here [_form.scss#L138](https://github.com/mercadolibre/chico/blob/v1.2.0/src/mobile/styles/_form.scss#L138)
