### ISSUE TITLE
Background Modal

### ISSUE THREAD

**Issue by jortizML** [mercadolibre/chico#1192]
Hola, estoy viendo que el modal luego de abrirlo y cerrarlo varias veces pierde el background.

Dejo unas capturas:

AR
http://prntscr.com/2y299y

UY
http://prntscr.com/2y2ai6
http://prntscr.com/2y2ao6

Les paso un dato que puede servir.
- Chrome Versión 33.0.1750.117

**Comment by hmammana** [comment]
Please review if it still is happening

**Comment by atma** [comment]
Cannot reproduce. Was autoresolved in some of previous versions.
