### ISSUE TITLE
Validations JS: Validation Message does not update

### ISSUE THREAD

**Issue by mgimenez** [mercadolibre/chico#1195]
Example:
$('#input_ico_inside').required().and().string();
Always displays the first error message, if required fault displays message required if full field the message is still required, it should show message string

**Comment by battaglr** [comment]
I can confirm this one. The validation always reports the right message, but the bubble never update the message.

Hope this saves time chasing the bug.

**Comment by battaglr** [comment]
This is related (or duplicated) to #1207.
