### ISSUE TITLE
Autocomplete: Padding in focus 

### ISSUE THREAD

**Issue by pmontesano** [mercadolibre/chico#1202]
When I change the padding of input, I have to change the padding in the focus because is different. 

Example:

Padding in input:
![image](https://cloud.githubusercontent.com/assets/2272384/2791336/a35b2d6c-cbc5-11e3-8a97-0592a569a172.png)

Padding in focus input:

![image](https://cloud.githubusercontent.com/assets/2272384/2791344/b7a44150-cbc5-11e3-886f-4e9d42be5db9.png)

**Comment by battaglr** [comment]
@pmontesano, I know this is old, but I can't reproduce it. I tried modifying the `padding` of a "regular" `input` in [Layout#Forms](http://chico.mercadolibre.com/2x/ui/layout/#forms) and the `padding` of an `input` with `Autocomplete` in [Components#Autocomplete](http://chico.mercadolibre.com/2x/ui/components/#autocomplete) and none of them had a different `padding` applied on `:focus` state.

This was more likely a problem with the search input itself.
