### ISSUE TITLE
Bug Autocomplete

### ISSUE THREAD

**Issue by pmontesano** [mercadolibre/chico#1206]
Cuando escribis en el input y te carga el autocomplete pero no seleccionadas nada de lo que te ofrece sino que le das enter a lo que tipeaste, no hace submit del form.

**Comment by marcoscaceres26** [comment]
@hmammana @pmontesano @ibarbieri This bug report has been duplicated in #1220 but adding a suggested solution in it's comments.

**Comment by hmammana** [comment]
@marcoscaceres26 I'm going to close it and leave the other open.
