### ISSUE TITLE
Bug: Modal in Myml doesn't appear using IE 

### ISSUE THREAD

**Issue by mauroluna** [mercadolibre/chico#1212]
Using IE (only tested in v8, 75%) with W7 in Myml when we click "?" doesn't appear the modal correctly.
![1](https://cloud.githubusercontent.com/assets/3043750/4121713/d187ba70-32bd-11e4-8ef7-4fb159c59539.png)
![2](https://cloud.githubusercontent.com/assets/3043750/4121716/d57a408a-32bd-11e4-8476-318c71d18a24.png)
![3](https://cloud.githubusercontent.com/assets/3043750/4121718/da2993ec-32bd-11e4-9c73-cd8ce1bc9433.png)

**Comment by hmammana** [comment]
It was fixed with v1.0.0
