### ISSUE TITLE
Popover: support for touch and click events on displays that supports both

### ISSUE THREAD

**Issue by lquintana** [mercadolibre/chico#1229]
Al popover le queda bindeado el evento touchend y deja de recibir el evento click.

No se están soportando ambos eventos porque es exclusivo, o uno y otro.

ch.onpointertap = (ch.support.touch) ? 'touchend' : 'click';

Esto pasa (al menos) en ultrabooks y dispositivos all-in-one que soportan tanto click con el pad y touch.

**Comment by atma** [comment]
Events module is extracted to [tiny.js](https://github.com/mercadolibre/tiny.js). Use `tiny.pointertap` as a unified event name o just `"pointertap"` when IE8 support is not required.
