### ISSUE TITLE
Autocomplete submit button not working when suggested option is highlighted

### ISSUE THREAD

**Issue by marcoscaceres26** [mercadolibre/chico#1230]
Steps to reproduce:
1. display autocomplete's popover on type
2. navigate through suggestion not selecting anyone but highlighting one of them
3. mouse click on submit button (while the highlighted suggestion remains that way).

popover will close, but submit functionality will keep not working despite future click on submit button.

[issue demo video](https://drive.google.com/a/mercadolibre.com/file/d/0B2Qban83RqXSNHFmbE43WWFQMWs/view)

**Comment by atma** [comment]
This issue is related to an implementation of entire form and not autocomplete directly. Also looks like it is already resolved in [original repo](/mercadolibre/homes-fend).
