### ISSUE TITLE
Carousel - Pagination parameter is obsolete

### ISSUE THREAD

**Issue by tauchter** [mercadolibre/chico#1241]
Even the pagination parameter is defaulted to false the pagination gets rendered anyways. The probable cause its that on the [plugin initialisation] (https://github.com/mercadolibre/chico/blob/master/src/shared/scripts/Carousel.js#L281) the following assertion is not done:
```
this._options.pagination !== false
```
Same thing its happening on  the [_updatePages function] (https://github.com/mercadolibre/chico/blob/master/src/shared/scripts/Carousel.js#L409)

**Comment by atma** [comment]
Instead of adding an additional checks where the exact value is not important better to use truthy/falsy values. In this case should be `if (this._options.pagination) { this._addPagination(); }`.

**Comment by tauchter** [comment]
I am on it, the PR is on the way.

**Comment by tauchter** [comment]
@atma Feel free to check the PR and make any necessary comment of what can be improved.

https://github.com/mercadolibre/chico/pull/1242
