### ISSUE TITLE
Autocomplete: bad UX when selecting the suggested item

### ISSUE THREAD

**Issue by atma** [mercadolibre/chico#1254]
[Current implementation](https://github.com/mercadolibre/chico/blob/2.0.0-alpha.1/src/shared/scripts/Autocomplete.js#L382) requires one more action from user to submit the form with a keyboard (enter key) since the selection always removes the focus with `blur`. After the selection the input field should be focused to permit the submission.

**Comment by hmammana** [comment]
@atma I understand the behavior and the difference between mobile & desktop, but would you like to talk it with someone in the design team and user research? Sol Vazquez(sol.velazquez@) could help you.
We can perform some test to stay tunned with the users when they press a enter key.

**Comment by atma** [comment]
I was thinking that when we doing some action on item select that is changing the URL, e.g. `autocomplete.on('select', function(){ location = slugify(query) })`, no matter is it focused or not. But when the user want to continue to fill another fields the focused field is more handy, like `type ↵ tab to focus the next field → type`. At least it should maintain the `tabindex`.
I will prepare the demo for the current version and I'll contact the user research team, thank you.

**Comment by atma** [comment]
This behaviour depends on implementation and no on the core functionality of autocomplete. Closed as unnecessary.
