### ISSUE TITLE
Margins added in focus state of buttons

### ISSUE THREAD

**Issue by jota-v** [mercadolibre/chico#1257]
In the :focus state of buttons a strange margin that was never previously defined is added and makes things in the layout to move.

https://github.com/mercadolibre/chico/blob/master/src/ui/styles/_buttons.scss#L12

Also check why line-height and and paddings are re-defined.

**Comment by atma** [comment]
Was resolved in 5bf5819d16f745ede98ca2221720d3ac1676af26.
