### ISSUE TITLE
Remove the :focus state from default button styles

### ISSUE THREAD

**Issue by atma** [mercadolibre/chico#1263]
Currently default button styles are also applied to [`:focus`](https://github.com/mercadolibre/chico/blob/v1.2.1/src/shared/styles/_buttons.scss#L8) button state. This produces a) overspecificity, b) complexity and c) larger code size.

**Comment by battaglr** [comment]
Sadly I'll have to close this since it's not aligned with the project's current objectives. :pensive:

Thanks for opening the issue. :grinning:
