### ISSUE TITLE
[Request] Nested Dropdowns

### ISSUE THREAD

**Issue by Bit-Dust** [mercadolibre/chico#1281]
Hi, I want to know if is a way to create a nested dropdowns. I need a ch dropdown menu with a many submenus. 

Regards!

**Comment by atma** [comment]
Sorry, but currently there is no official support for nested dropdowns. This functionality is considered as outdated UX pattern and has no sense on mobile devices.
But you can add some extra CSS and put a nested level inside the dropdown item to achieve this functionality by with no additional JS.
