### ISSUE TITLE
Missing sass variable for link color

### ISSUE THREAD

**Issue by jvnni** [mercadolibre/chico#1313]
Link `:visited` state color is correct: `$link-visited-color`, link color variable references the main color of the theme, but needs to have its own independent variable.

Code reference:
![screen shot 2016-04-04 at 17 35 08](https://cloud.githubusercontent.com/assets/437205/14284719/1e9ec670-fb1f-11e5-9c5c-73ca086371d0.png)

**Comment by battaglr** [comment]
Nice catch, @jvnni! Would you like to make a PR? If not, I can do this tonight.
