### ISSUE TITLE
Tiny dependecy

### ISSUE THREAD

**Issue by escudero89** [mercadolibre/chico#1326]
It seems that chico makes use of `tiny.js`, as it's listed in its dependencies (in `package.json`).

However, if you use `chico.js` which appears in the `dist` folder (without including `tiny` in your own project), it fails. Such configuration (and requirement) is not explained in the README (or at least, I didn't found any).

Furthermore, what if I don't want `tiny` on my project (e.g. _i am using jquery instead_)? It would be awesome if there would be some kind of mechanism which uses `tiny` or `jQuery` or whatever available, avoiding forcing onto the user the requirement of using `tiny.js`.

**Comment by battaglr** [comment]
Thanks, @escudero89!

> However, if you use `chico.js` which appears in the `dist` folder (without including `tiny` in your own project), it fails. Such configuration (and requirement) is not explained in the README (or at least, I didn't found any).

I'll add that to the readme!

> Furthermore, what if I don't want `tiny` on my project (e.g. _i am using jquery instead_)? It would be awesome if there would be some kind of mechanism which uses `tiny` or `jQuery` or whatever available, avoiding forcing onto the user the requirement of using `tiny.js`.

That's an interesting idea! I think it would require some analys

**Comment by escudero89** [comment]
No prob.

Regarding the second point, I was thinking something along the lines of:

```js
if (jQuery || $) {
    use_jquery = true;
}
```

_(pseudo-code at its finest)_

What could `use_jquery` mean? Well, we could replace the `tiny` declaration to use `jQuery` instead. I think that was what I meant when I wrote that issue back in mid 2016.

Greetings and thanks for the update.

**Comment by battaglr** [comment]
@escudero89, thanks! I'll check if that's feasible. I think this may help with the transition from v1.x to v2.x.

**Comment by battaglr** [comment]
@escudero89,

1. Regarding the confusion about Tiny, I added an explicit reference to "dependencies" in the official website: http://chico.mercadolibre.com/2x/ui/getting-started/#dependencies.

2. Regarding the ability to switch between jQuery/Tiny as dependency, I don't see that being added since it's not aligned with the project's current objectives. It is a cool idea, thou. :man_dancing:
