### ISSUE TITLE
Missing documentation for form component (v2.x)

### ISSUE THREAD

**Issue by amireynoso** [mercadolibre/chico#1336]
There's no documentation in the section Common CSS for form use (input, selects, row, use with icons, etc).

**Comment by battaglr** [comment]
@amireynoso, we could add something similar to [Components#Validations](http://chico.mercadolibre.com/components/#validations). Or maybe, that example is all we need. What do you think?

**Comment by amireynoso** [comment]
@battaglr Something like that sounds about right! But in the Common CSS section, with only markup  and no functionality, what do you think? For the most common use cases at least.

**Comment by battaglr** [comment]
@amireynoso, yup, I agree. I'll add that.

**Comment by battaglr** [comment]
@amireynoso, I've added examples in [Layout#Forms](http://chico.mercadolibre.com/2x/ui/layout/#forms). Let me know what do you think.

Thanks for the suggestion. :grinning:
