### ISSUE TITLE
Validations wrong info in API doc

### ISSUE THREAD

**Issue by HGARZON** [mercadolibre/chico#1339]
'success'  event is showing the wrong event in the example.

URL: http://chico.mercadolibre.com/api-doc/current/ui/ch.validation/

Print error:

![screen shot 2017-01-26 at 11 06 13 am](https://cloud.githubusercontent.com/assets/1180630/22333969/7961ab5a-e3b7-11e6-8c50-9e103eaab4f7.png)

**Comment by battaglr** [comment]
Nice catch, @HGARZON! Would you like to open a PR for this (if you can't, just let me know)? I'll put this on the next release.

**Comment by HGARZON** [comment]
Thanks @battaglr ! Please assign me the issue so I can make the PR.

**Comment by battaglr** [comment]
Closed by #1344.

**Comment by battaglr** [comment]
We should add this in the `v1.x.x` branch too. I'll take care of that. Thanks for the help @HGARZON. 😉

**Comment by battaglr** [comment]
Closed by #1348.
