### ISSUE TITLE
List Options: It should show the background color when it's being touched

### ISSUE THREAD

**Issue by hmammana** [mercadolibre/chico#866]
Webkit 530.17, Android 2.1-update1
	Webkit 533.1, Android 2.2, 2.2.1, 2.2.2, 2.2.3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7
	SymbianOS, SymbianOS

**Comment by hmammana** [comment]
Please review if the traffic is relevant on those devices.

**Comment by atma** [comment]
Closed due to low traffic volume.
