### ISSUE TITLE
Icons: add List Options arrows to the sprite

### ISSUE THREAD

**Issue by hmammana** [mercadolibre/chico#867]
WebFont not supported in the following test browsers: 
    Webkit 530.17, Android 2.1-update1
    IE 9.0, Windows Phone
    Blackberry, Blackberry, devices: [ PlayBook, BB6 & BB7 ]
    SymbianOS, SymbianOS
    Safari 6533.18.5, iOS 4.0

Reference: http://blog.kaelig.fr/post/33373448491/testing-font-face-support-on-mobile-and-tablet

**Comment by hmammana** [comment]
Please review if the traffic is relevant on those devices.

**Comment by atma** [comment]
Due to low market share implement fallback with a common unicode symbols like `▶︎` or  `◀︎`.
Additional review required.

**Comment by battaglr** [comment]
I'll close this due to inactivity. If it's still relevant, please, feel free to comment.
