### ISSUE TITLE
Mediator: create a mediator object to avoid bind custom events to DocumentElement.

### ISSUE THREAD

**Issue by pazguille** [mercadolibre/chico#948]
```js
// some code
ch.mediator.emit('changeLayout');
```

```js
// some code
ch.mediator.on('changeLayout', bar);
```

**Comment by hmammana** [comment]
It could be used for other purpose too.

**Comment by atma** [comment]
@hmammana In the latest version we have a listener for the custom events bound to a `window.document`, like so
```
ch.Event.addListener(document, ch.onlayoutchange, this._refreshPositionListener);
ch.Event.dispatchCustomEvent(document, ch.onlayoutchange);
```
`ch.onlayoutchange` is the only custom event. Should we change this approach for a mediator? What do you think?

**Comment by hmammana** [comment]
I think it's not really necessary.

**Comment by atma** [comment]
Thank you @hmammana. Closing, at least for now.
